//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_oct130625.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStudent
    {
        public int ID { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        [DisplayFormat(DataFormatString = "{0: MM/dd/yyyy}")]
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<double> FeesPaid { get; set; }
    }
}
